"""Initial schema with conversation threads and messages

Revision ID: 1b1ed9e0b07a
Revises: 
Create Date: 2025-11-06 23:16:37.645588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b1ed9e0b07a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_threads',
    sa.Column('openai_thread_id', sa.String(length=255), nullable=False, comment='OpenAI thread identifier'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of last activity in the thread'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='Total number of messages in the thread'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total tokens used across all messages'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_threads_openai_thread_id'), 'conversation_threads', ['openai_thread_id'], unique=True)
    op.create_table('messages',
    sa.Column('thread_id', sa.UUID(as_uuid=False), nullable=False, comment='Foreign key to conversation_threads table'),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False, length=20), nullable=False, comment='Message role: user or assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content text'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='Number of tokens in the prompt'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='Number of tokens in the completion'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['thread_id'], ['conversation_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    
    # Drop old tables with CASCADE to handle dependencies
    op.execute('DROP TABLE IF EXISTS agent_messages CASCADE')
    op.execute('DROP TABLE IF EXISTS agent_sessions CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop our new tables
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_threads_openai_thread_id'), table_name='conversation_threads')
    op.drop_table('conversation_threads')
    # ### end Alembic commands ###
